# Generated by Django 2.2.1 on 2019-05-29 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.TextField(max_length=15)),
                ('phone', models.IntegerField()),
                ('dob', models.DateField(default=datetime.date.today)),
                ('address', models.TextField(max_length=150)),
                ('profilepic', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('Author', models.CharField(max_length=100)),
                ('Dop', models.TextField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('content', models.TextField()),
            ],
        ),
    ]
