# Generated by Django 2.2.1 on 2019-06-03 22:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('phone', models.IntegerField()),
                ('dob', models.DateField(default=datetime.date.today)),
                ('address', models.TextField(max_length=150)),
                ('profilepic', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('Author', models.CharField(max_length=100)),
                ('Dop', models.TextField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('content', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accountid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Account')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Book')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='roleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Role'),
        ),
    ]
