# Generated by Django 2.2.1 on 2019-05-29 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190529_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='roleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Role'),
        ),
        migrations.CreateModel(
            name='AccountBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accountid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Account')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Book')),
            ],
        ),
    ]
