# Generated by Django 2.2.1 on 2019-06-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_account_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='randNum',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
