# Generated by Django 2.2.1 on 2019-06-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190604_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='omer', max_length=100),
            preserve_default=False,
        ),
    ]
