# Generated by Django 2.2.1 on 2019-06-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190604_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profilepic',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
