# Generated by Django 2.2.1 on 2019-06-04 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190604_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone',
        ),
    ]
