# Generated by Django 2.2.1 on 2019-06-04 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_account_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='roleid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Role'),
        ),
    ]
