# Generated by Django 2.2.1 on 2019-06-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_accountbook'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ebooks',
            field=models.ManyToManyField(blank=True, null=True, to='store.Book'),
        ),
    ]
