# Generated by Django 2.2.1 on 2019-06-10 11:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_profile_ebooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=100)),
                ('dop', models.DateField(default=datetime.date.today)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sale', models.IntegerField()),
                ('ispn', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('copies', models.IntegerField(default=1)),
                ('rate', models.FloatField(default=0, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='ebooks',
            field=models.ManyToManyField(blank=True, null=True, to='users.Book'),
        ),
    ]
