# Generated by Django 2.2.1 on 2019-06-03 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190531_0253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
