# Generated by Django 2.2.1 on 2019-06-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190610_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='default.jpg', null=True, upload_to='book_pics'),
        ),
    ]
