# Generated by Django 2.2.1 on 2019-06-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roomName', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
