# Generated by Django 2.2.1 on 2019-06-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='count',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
