# Generated by Django 2.2.1 on 2019-06-07 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='book_pics')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Book')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
