# Generated by Django 2.2.1 on 2019-06-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190607_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_profile',
            name='image',
            field=models.ImageField(default='empty_cover.png', upload_to='book_pics'),
        ),
    ]
