# Generated by Django 2.2 on 2019-06-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190608_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='book_pics'),
        ),
    ]
