# Generated by Django 2.2.1 on 2019-06-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20190610_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_orderd',
            new_name='is_ordered',
        ),
    ]
